# Generated by Django 4.1.1 on 2022-11-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='gender',
        ),
    ]
